### ISSUE TITLE
READMEの"MacでJDK7以上を使って動作させる設定"がリンク切れ

### ISSUE THREAD

**Issue by posaunehm** [kyonmm/stac2014-handson-document#1]
> MacでJDK7以上を使って動作させる設定:
> http://blog.yotchang4s.org/2014/04/13/mac_java8_intellij_idea_13_1_1

↑がリンク切れしています。（恐らく該当blogのドメイン有効期限切れ）

設置先blogがGithubにホスティングしていたので、以下から内容自体は見れそうです。
- https://github.com/yotchang4s/blog.yotchang4s.org/blob/master/2014/04/13/mac_java8_intellij_idea_13_1_1.rst

**Comment by kyonmm** [comment]
対応しました！よかったら、クローズにしてください。

**Comment by posaunehm** [comment]
ありがとうございます！
